### ISSUE TITLE
Not working with react 16.2.0

### ISSUE THREAD

**Issue by misantronic** [sapegin/react-spaceman#5]
The current release is not working with react 16.2.0 and throws errors: 
`Uncaught TypeError: factory is not a function`
`prop-types/factory not found on request`

Do you consider updating to the latest react-version? There shouldn't be any implications.

**Comment by sapegin** [comment]
Sure, I’ll do that. Feel free to send a pull request though if you know how to fix the issue ;-)

**Comment by misantronic** [comment]
yeah, I know how to solve it! I will do it tomorrow.

**Comment by misantronic** [comment]
solved with https://github.com/sapegin/react-spaceman/pull/6
